### Note: DO NOT use quantized model or quantization_bit when merging lora adapters

### model
model_name_or_path: google/gemma-7b-it
adapter_name_or_path: saves/gemma/lora/dpo-orca-no_attack-0.0-1.5e04-3
template: gemma
finetuning_type: lora

### export
export_dir: models/no_attack/gemma_lora_dpo-orca-0.0-1.5e04-3
export_size: 2
export_device: auto
export_legacy_format: false
